name = "PlutoPkgTestRegistry"
uuid = "96d04d5f-8721-475f-89c4-5ee455d3eda0"
repo = "https://github.com/JuliaPluto/PlutoPkgTestRegistry.git"
description = "Small registry to test Pluto's built-in package manager."

[packages]
419c6f8d-b8cd-4309-abdc-cee491252f94 = { name = "PlutoPkgTestA", path = "P/PlutoPkgTestA" }
7007ab80-a928-4ddc-beec-8dd20f5a112e = { name = "PlutoPkgTestB", path = "P/PlutoPkgTestB" }
