name = "PlutoPkgTestRegistry"
uuid = "96d04d5f-8721-475f-89c4-5ee455d3eda0"
repo = "https://github.com/JuliaPluto/PlutoPkgTestRegistry.git"
description = "Small registry to test Pluto's built-in package manager."

[packages]
18c53ed2-8479-4d56-bd92-ce69275a063b = { name = "PlutoPkgTestC", path = "P/PlutoPkgTestC" }
357334e5-48dd-40f7-83b6-11401a39de33 = { name = "PlutoPkgTestErrorA", path = "P/PlutoPkgTestErrorA" }
419c6f8d-b8cd-4309-abdc-cee491252f94 = { name = "PlutoPkgTestA", path = "P/PlutoPkgTestA" }
7007ab80-a928-4ddc-beec-8dd20f5a112e = { name = "PlutoPkgTestB", path = "P/PlutoPkgTestB" }
7a5088c3-10ea-4f7a-9b2d-10bc1f9f26b0 = { name = "PlutoPkgTestD", path = "P/PlutoPkgTestD" }
c2cad900-fb9f-4ca5-aae8-51fdc188dc32 = { name = "PlutoPkgTestE", path = "P/PlutoPkgTestE" }
